# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: â­• CI
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  lint:
    name: â¬£ Lint
    environment: preview
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Set NPM registry auth
        run: pnpm install

      - name: ğŸ”¬ Lint
        run: pnpm run lint

  sveltecheck:
    name: â¬£ Svelte-check & TS Check
    environment: preview
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: ğŸ”» Install dependencies
        run: pnpm install

      - name: ğŸ”¬ Lint
        run: pnpm run check

  vitest:
    name: âš¡ Vitest
    environment: preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: ğŸ”» Install dependencies
        run: pnpm install

      - name: âš¡ Run vitest
        run: pnpm run test:unit

  playwright:
    name: ğŸ­ Playwright
    environment: preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend

    timeout-minutes: 60
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ„ Copy test env vars
        run: cp .env.example .env

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: ğŸ”» Install dependencies
        run: pnpm install

      - name: Setup Playwright
        run: pnpm dlx playwright install --with-deps

      - name: ğŸ­ Playwright tests
        run: pnpm playwright test

