# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: â­• CI
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: â¬£ Lint
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set NPM registry auth
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: ğŸ”½ Install dependencies
        run: pnpm install
          

      - name: ğŸ”¬ Lint
        run: pnpm run lint

  sveltecheck:
    name: â¬£ Svelte-check & TS Check
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set NPM registry auth
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: ğŸ”½ Install dependencies
        run: pnpm install

      - name: ğŸ”¬ Lint
        run: pnpm run check

  vitest:
    name: âš¡ Vitest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set NPM registry auth
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: ğŸ”½ Install dependencies
        run: pnpm install

      - name: âš¡ Run vitest
        run: pnpm run test:unit

  playwright:
    name: ğŸ­ Playwright
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend

    timeout-minutes: 60
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
  
      - name: Set NPM registry auth
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: ğŸ”½ Install dependencies
        run: pnpm install

      - name: ğŸ— Build
        run: pnpm run build

      - name: ğŸ­ Playwright tests
        run: pnpm run test
