# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: â­• CI
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  lint:
    name: â¬£ Lint
    environment: preview
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ðŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Set NPM registry auth
        run: pnpm install

      - name: ðŸ”¬ Lint
        run: pnpm run lint

  vitest:
    name: âš¡ Vitest
    environment: preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ðŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: ðŸ”» Install dependencies
        run: pnpm install

      - name: âš¡ Run vitest
        run: pnpm run test:unit

  playwright:
    name: ðŸŽ­ Playwright
    environment: preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/svelte-frontend

    timeout-minutes: 60
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ðŸ„ Copy test env vars
        run: cp .env.example .env

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ðŸ“¥ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: ðŸ”» Install dependencies
        run: pnpm install

      - name: ðŸ“¥ Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: ðŸŽ­ Playwright tests
        run: |
          pnpm run dev
          pnpm exec node_modules/@playwright/test/cli.js test

      - name: ðŸ“Š Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
